version: '3.7'
services:
  postgres:
    image: postgres:15-alpine
    restart: always
    container_name: semestral_work_db
    environment:
      - POSTGRES_USER=kornumic
      - POSTGRES_PASSWORD=kornumic
      - POSTGRES_DB=semestral_db
    ports:
      - '5432:5432'
    volumes:
      - .docker/postgres-data:/var/lib/postgresql/data
  api:
    image: cz.cvut.fit.tjv.semestral.api
    depends_on:
      - postgres
    ports:
      - '8080:8080'
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://semestral_work_db/semestral_db
      SPRING_DATASOURCE_USERNAME: kornumic
      SPRING_DATASOURCE_PASSWORD: kornumic
